# Workflow 1: Testing Node.js Application
defaults:
  run:
    shell: bash

name: Workflow 1 - Node.js Tests

on:
  push:
    branches:
      - main

jobs:
  node-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test