# Workflow 2: Docker Image Build and Deploy

defaults:
  run:
    shell: bash

name: Workflow 2 - Docker Build and Deploy

on:
  workflow_run:
    workflows:
      - Workflow 1 - Node.js Tests
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-testing-js:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/api-testing-js:latest
